name: PyLint
 
on: [push, pull_request]
 
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
 
      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black
      - name: Remove unused imports and variables
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --ignore-init-module-imports ./assistant/
      - name: lint with isort and black
        run: |
          isort .
          black .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Remove Unused Imports.'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Starkgangs
          commit_user_email: Starkgangz@gmail.com
          commit_author: Starkgangs <Starkgangz@gmail.com>
